# See http://jekyllrb.com/docs/configuration/.
name: Atlaas - Atlas de l'Internet Public et Citoyen
# No permalink
permalink: none
# Currently using github project domain
root: /atlaas
# Markdown interpreter
markdown: kramdown
# prose.io settings
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  siteurl: "http://makinacorpus.github.io/atlaas"
  media: "media"
  ignore:
      - index.html
      - _config.yml
      - /_layouts
      - /scripts
      - /styles
      - /images
      - CNAME
      - favicon.ico
      - robots.txt
      - /pages/news.md
      - README.md
  metadata:
    "_posts":
      - name: "layout"
        field:
          element: "hidden"
          value: "static"
